### ISSUE TITLE
ModuleNotFoundError: NO module named 'binance.spot'

### ISSUE THREAD

**Issue by DevDjino** [Forte42/Trading_Bot_9000#37]
Hello I am starter in developing and getting issue with multiple errors when I try to run the command to start the bot  python3 get_data.py sh run_signal.sh python3 tradebot.py

here a screenshot of the errors I'm getting  
![Screenshot from 2022-10-18 12-34-17](https://user-images.githubusercontent.com/42117838/196420087-23f8b163-39f1-4211-9656-3b1b6265e8fe.png)

**Comment by Forte42** [comment]
Hey there,

You need to install the python-binance module, I updated our
requirements.txt and readme.

Cheers,
Garrett

**Comment by DevDjino** [comment]
Hello thanks for the quick response

After installing the python-binance module I start the code again and a new error appear but this time says:

ModuleNotFoundError: No module named 'binance.spot'

![Screenshot from 2022-10-19 15-53-21](https://user-images.githubusercontent.com/42117838/196726833-9717a85c-9bb7-4071-a723-1951fbf47fe8.png)

**Comment by DevDjino** [comment]
and when I install the riqueriments.txt some modules are not installed and I need to install them one by one like the apscheduler==3.9.1
python-binance==1.0.16 and the python-dotenv==0.21.0 you have any idea what could be the problem?

**Comment by Forte42** [comment]
Hey there,

So if you've cloned my repo you need to do so again from my repo so you
have the new changes to the requirements.txt file. Also, can you confirm
how you installed python-binance? Did you run "pip install python-binance"?

Finally, you left out the bottom of the exception in your included
screenshot,
Garrett

**Comment by DevDjino** [comment]
Hello,

yes I run "pip install python-binance" because I was not able to install from the requirements.txt

I cloned the repo again and follow all the steps and I get the ModuleNotFoundError: No module named 'binance.spot'

here the screenshots of all process I did:
![Screenshot from 2022-10-19 19-17-59](https://user-images.githubusercontent.com/42117838/196774997-e689510b-63d4-4155-8000-1f37542e3ef2.png)
![Screenshot from 2022-10-19 19-18-31](https://user-images.githubusercontent.com/42117838/196775003-57c5f829-382e-427b-95ef-afd158ead04f.png)
![Screenshot from 2022-10-19 19-24-11](https://user-images.githubusercontent.com/42117838/196775012-92778c95-0234-42fe-bc5c-f4d83ffa86e3.png)
![Screenshot from 2022-10-19 19-24-56](https://user-images.githubusercontent.com/42117838/196775020-6798c78a-ed67-40d0-8d1a-c6ee5a255827.png)

**Comment by Forte42** [comment]
Ok, from one of my teammates:

oh i bet i know what's going on....  have him run
python3 -m pip install python-binance
I bet he has multiple versions of python installed on his system.

If that doesn't work I'll send you over to him, he runs linux too and will
be more able to help you.

Garrett

**Comment by DevDjino** [comment]
unfortunately don't work for me running 'python3 -m pip install python-binance'

![Screenshot from 2022-10-19 20-10-09](https://user-images.githubusercontent.com/42117838/196783281-e457b8d8-7030-4d8f-9f3e-a51efeca3c44.png)
![Screenshot from 2022-10-19 20-10-37](https://user-images.githubusercontent.com/42117838/196783293-3b59d72a-82ef-459f-800f-198d468cdcfd.png)

**Comment by DevDjino** [comment]
can you say what machine you are running the code?

I have windows too and I could try to run the code tomorrow on windows, now it's getting too late for me, need to sleep.

**Comment by Forte42** [comment]
I'm running a windows computer but my teammate runs Linux.

Talk later

**Comment by DevDjino** [comment]
Hi Garrett,

I try to run the code on windows but still get the same error 

![err](https://user-images.githubusercontent.com/42117838/196901124-fb4390e6-397f-4d93-92fd-e55f6604b815.png)
![errr](https://user-images.githubusercontent.com/42117838/196901151-1aaf5080-e2b7-4569-b1c2-e28a91ab3e7a.png)

**Comment by DevDjino** [comment]
the error seems something with the code line "from binance.spot import Spot" but I'm not sure

**Comment by DevDjino** [comment]
I fixed the error [ModuleNotFoundError: NO module named 'binance.spot'] by changing the code line  "from binance.spot import Spot"  with "from binance.client import Client" on the python files below:

from folder data_acquisition the files:

get_binance_btc_0m.py
get_binance_btc_1d.py
get_binance_btc_1m.py
get_binance_btc_30m.py
get_binance_btc_3m.py
get_binance_ohlcv_bar.py

from the folder tradebot the files:

b.py
get_binance_balances.py
order_functions.py

**Comment by DevDjino** [comment]
But by doing that I mess up a lot of things on the code here is a screenshot:

![code](https://user-images.githubusercontent.com/42117838/196928781-fcfe1444-dc33-4880-a594-a395f49b7eeb.png)

**Comment by DevDjino** [comment]
Just find the Fix, to fix the issue I run "pip install binance-connector", and I find solution here: https://github.com/binance/binance-connector-python

**Comment by Forte42** [comment]
Nice, thank you very much
